apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts
  labels:
    app: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      service: accounts
  template:
    metadata:
      labels:
        app: sample-app
        service: accounts
    spec:
      containers:
        - name: webapp
          image: accounts.azurecr.io/accounts:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:8080
            - name: WebApiBaseAddress
              value: http://webapi