apiVersion: v1
kind: Service
metadata:
  name: accounts
  labels:
    app: sample-app
    service: accounts
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    service: accounts